[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.sdist]
exclude = [".idea", "tmp", "dist", ".tox", ".pytest_cache"]

[tool.flit.metadata]
module = "facet"
author = "Boston Consulting Group (BCG)"
home-page = "https://github.com/BCG-Gamma/facet"
description-file = "pypi_description.rst"
dist-name = "gamma-facet"
license = "Apache Software License v2.0"

requires = [
    # direct requirements of gamma-facet
    "gamma-pytools  ~=1.2,>=1.2.1",
    "matplotlib     ==3.*",
    "numpy          >=1.17,<1.21a",
    "packaging      ==20.*",
    "pandas         >=0.24,<2a",
    "scipy          ~=1.2",
    "shap           >=0.34,<0.40",
    "sklearndf      ~=1.2",
    # additional requirements of shap 0.38
    "ipython        >=7",
]

requires-python = "~=3.6"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]

[tool.flit.metadata.requires-extra]
testing = [
    "pytest ~= 5.2",
    "pytest-cov ~= 2.8",
    "flake8 ~= 3.8",
    "flake8-comprehensions ~= 3.2",
    "isort ~= 5.5",
]
docs = [
    "sphinx == 3.4.*",
    "sphinx-autodoc-typehints == 1.11.*",
    "pydata-sphinx-theme == 0.4.*",
    "jinja2 ~= 2.11",
    "nbsphinx ~= 0.8.5",
    "jupyter == 1.*",
    "docutils == 0.16.*",
    "xlrd ~= 1.2",
    "m2r == 0.2.*"
]

[tool.flit.metadata.urls]
Documentation = "https://bcg-gamma.github.io/facet/"
Repository = "https://github.com/BCG-Gamma/facet"

[build.matrix.min]
# direct requirements of gamma-facet
gamma-pytools  = "=1.2.1"
matplotlib     = "=3.0.*"
numpy          = "=1.17.*"
packaging      = "=20.*"
pandas         = "=0.24.*"
python         = "=3.6.*"
scipy          = "=1.2.*"
shap           = "=0.34.*"
sklearndf      = "=1.2.0"
# additional minimum requirements of sklearndf
boruta         = "=0.3.*"
lightgbm       = "=3.0.*"
scikit-learn   = "=0.21.*"
# additional minimum requirements of gamma-pytools
joblib         = "=0.14.*"
typing_inspect = "=0.4.*"

[build.matrix.max]
# direct requirements of gamma-facet
gamma-pytools  = "~=1.2"
matplotlib     = "~=3.3"
numpy          = ">=1.20,<2a"
packaging      = "=20.*"
pandas         = "~=1.2"
python         = "~=3.8"
scipy          = "~=1.5"
shap           = "=0.39.*"
sklearndf      = "~=1.2"
# additional requirements of sklearndf
boruta         = "~=0.3"
lightgbm       = "~=3.2"
scikit-learn   = "~=0.24"
# additional maximum requirements of gamma-pytools
joblib         = "=1.*"
typing_inspect = "~=0.7"

[tool.black]
# quiet = "True"
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | data
    | docs
    | notebooks
    | sphinx
  )/
)
'''
